options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build the container using the Dockerfile we just created
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/run-repo/greenfieldlocalhubexam:$COMMIT_SHA', '.']

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/run-repo/greenfieldlocalhubexam:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'greenfieldlocalhubexam'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/run-repo/greenfieldlocalhubexam:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--allow-unauthenticated'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/run-repo/greenfieldlocalhubexam:$COMMIT_SHA'
